### ISSUE TITLE
Setting up class C in python

### ISSUE THREAD

**Issue by Squifer** [AmedeeBulle/pyrak811#14]
When trying to run Class C in python:
```
CLASS = '2'
lora.set_config(dev_eui=DEV_EUI,
                        app_key=APP_KEY,
                        class=CLASS)
```
I get an invalid syntax error on class. class is a keyword meaning it is a reserved word that cannot be used as a variable/function name. Is there a workaround for this?

**Comment by ryanteck** [comment]
Hi @Squifer ,

I don't think it supports Class C at the moment?

**Comment by Squifer** [comment]
Hi @ryanteck ,

Oh... will it be supported anytime soon?

**Comment by AmedeeBulle** [comment]
According to the RAK811 documentation, the V3.0.x firmware has Class C support.

I don't have access to a class C network to test...
