### ISSUE TITLE
[Errno 99] LoRa join failed

### ISSUE THREAD

**Issue by mxzahedlim** [AmedeeBulle/pyrak811#20]
My project used RPi 3B+ pair with LoRa Node pHAT RAK811-H

i follow all instruction at README.md but i always get error
Traceback (most recent call last):
  File "/home/pi/Desktop/lora.py", line 11, in <module>
    lora.join()
  File "/usr/local/lib/python3.7/dist-packages/rak811/rak811_v3.py", line 501, in join
    self._send_command('join', timeout=self._event_timeout)
  File "/usr/local/lib/python3.7/dist-packages/rak811/rak811_v3.py", line 254, in _send_command
    raise Rak811ResponseError(response[len(RESPONSE_ERROR):])
rak811.rak811_v3.Rak811ResponseError: [Errno 99] LoRa join failed
>>> 
how to fix it , i dont know how to do.
Thanks you

**Comment by AmedeeBulle** [comment]
The Error 99 -- `LoRa join failed` -- is returned by the RAK811 module when it can't connect to the LoRaWan network.

This typically happens when:
- `app_eui` and/or `app_key` are incorrect
- there is no LoRaWan gateway in your proximity

**Comment by AmedeeBulle** [comment]
Closing sue as no feedback from OP
