### ISSUE TITLE
Send to specific channel

### ISSUE THREAD

**Issue by varna9000** [AmedeeBulle/pyrak811#5]
How do you send a payload on specific channel number?

**Comment by ryanteck** [comment]
Hi @varna9000 ,

Do you mean a specific LoRa Frequency (Such as only on 868.1 Mhz) or a specific lora port? (Instead of the default 1)

**Comment by varna9000** [comment]
Yes, I think it's the frequency I'm looking for.

**Comment by ryanteck** [comment]
Hi @varna9000 , Currently it isn't possible in the library but we'll get it implemented shortly.

Can I check which frequency you need yours to broadcast on?

**Comment by varna9000** [comment]
I'm sorry it seems I made a mistake. I'm on a standard frequency :) Great library, thanks for your efforts.

**Comment by AmedeeBulle** [comment]
As this issue is inactive for quite some time now, I am closing it.
If you feel it deserve additional attention, feel free to reopen it.
