### ISSUE TITLE
Link to User guide not working

### ISSUE THREAD

**Issue by aal7** [AmedeeBulle/pyrak811#9]
Hi,

The link in the readme to the user guide v1.5 doesn't seem to be working.
Could you update it?

Thanks

**Comment by ryanteck** [comment]
Hi @aal7 ,

While I couldn't find a copy of the V1.5 instructions I did find a copy of V1.4 which has most of the commands (I can't actualy remember a difference between V1.4 & V1.5).

I've uploaded this to a new folder in the respository called DOCS.

Hopefully this is all fine for you.
